# Generated by Django 2.2 on 2020-08-24 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0003_auto_20200824_1057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issues',
            old_name='types',
            new_name='types_old',
        ),
    ]
