# Generated by Django 2.2 on 2020-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0004_auto_20200824_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='issue_set', to='issue_tracker.Type'),
        ),
    ]
