# Generated by Django 2.2 on 2020-08-24 11:21

from django.db import migrations


def transfer_types(apps, schema_editor):
    Issues = apps.get_model('issue_tracker.Issues')
    for issue in Issues.objects.all():
        issue.types.set(issue.types_old.all())

def rollback_transfer(apps, schema_editor):
    Issues = apps.get_model('issue_tracker.Issues')
    for issue in Issues.objects.all():
        issue.types_old.set(issue.types.all())


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0005_issues_types'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
