# Generated by Django 2.2 on 2020-08-24 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0008_auto_20200824_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='type',
        ),
    ]
