# Generated by Django 2.2 on 2020-08-28 18:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0009_remove_issues_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='Краткое описание'),
        ),
    ]
