# Generated by Django 2.2 on 2020-08-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0011_auto_20200828_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='summary',
            field=models.CharField(max_length=200, verbose_name='Краткое описание'),
        ),
    ]
