# Generated by Django 2.2 on 2020-08-28 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0012_auto_20200828_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(100)], verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='issues',
            name='summary',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='Краткое описание'),
        ),
    ]
