# Generated by Django 2.2 on 2020-09-25 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue_tracker', '0014_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='issue_tracker.Project', verbose_name='Проект'),
            preserve_default=False,
        ),
    ]
